"""empty message

Revision ID: 4a14afc4c70a
Revises: eafdd01de10f
Create Date: 2021-03-09 18:27:25.237107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a14afc4c70a'
down_revision = 'eafdd01de10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
