"""empty message

Revision ID: b0aa0baa1979
Revises: feabf9afec85
Create Date: 2021-03-09 18:46:41.634568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0aa0baa1979'
down_revision = 'feabf9afec85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
