"""empty message

Revision ID: feabf9afec85
Revises: d95bf28639fa
Create Date: 2021-03-09 18:41:07.277415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feabf9afec85'
down_revision = 'd95bf28639fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
